config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: "static_pages#about"
  get "/login", to: "sessions#new"
  delete "/logout", to: "sessions#destroy"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users
  resources :sessions, only: [:create]
  resources :posts, only: [:create,:destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :content, presence: true,length: {maximum:250}

  default_scope {order(created_at: :desc)}

  mount_uploader :picture, PictureUploader

  validate :picture_size

  private
    def picture_size
      error.add(:picture, "should be less than 5mb ") if picture.size > 5.megabytes
    end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name:"User"
    belongs_to :followed, class_name: "User"

    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :posts
    
    validates :name, presence: true, 
                    length: {minimum: 3, maxmum: 20}


    before_save {email.downcase! }
    EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
    validates :email, presence: true,
                    length: { maximum: 30 },
                    format: { with: EMAIL_REGEX},
                    uniqueness: {case_sensitive: false}

    # this is method has_secured_password
    has_secure_password
    validates :password, length: {minimum: 6}, allow_nil: true

    has_many :active_relationships, class_name: "Relationship",
                                    foreign_key: "follower_id",
                                    dependent: :destroy
    has_many :following,    through: :active_relationships,
                            source: :followed
    has_many :passive_relationships, class_name: "Relationship",
                                    foreign_key: "followed_id",
                                    dependent: :destroy
    has_many :followers, through: :passive_relationships, source: :follower

    def follow(other_user)
        following << other_user
    end

    def unfollow(other_user)
        following.delete(other_user)
    end

    def following?(other_user)
        following.include?(other_user)
    end

    def feed
        following_ids = "SELECT followed_id FROM relationships
                        WHERE follower_id = :user_id"
        Post.where("user_id IN (#{following_ids})
                    OR user_id = :user_id",user_id: id)

    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

    def create
        @post = current_user.posts.build(post_params)
        if @post.save
            redirect_to root_url
        else
            @posts = current_user.posts.paginate(page: params[:page], per_page: 5)
            render "users/home_feed"
        end
    end

    def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to root_url
    end


    private
        def post_params
            params.require(:post).permit(:content,:picture)
        end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    def create
        user = User.find(params[:followed_id])
        current_user.follow(user)
        redirect_to user
    end

    def destroy 
        user  = Relationship.find(params[:id]).followed
        current_user.unfollow(user)
        redirect_to user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email])
    
    if user && user.authenticate(params[:session][:password])
      login(user)
      flash[:success] = "Successfully logged in."
      redirect_to root_url
    else
      flash[:danger] = "Invalid Credentials." 
      render "new"
    end
  end

  def destroy
    logout
    flash[:info] = "Successfully logged out!"
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @post =Post.new
      @posts = current_user.feed.paginate(page: params[:page],per_page: 5)

      render "users/home_feed"
    end
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]
  before_action :require_admin, only: [:destroy]
  before_action :correct_user, only: [:edit, :update]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Successfully Resistered!"
      redirect_to root_url
    else
      render "new"
    end
  end

  def index
    @users = User.paginate(page: params[:page], per_page: 10)
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.paginate(page: params[:page], per_page: 10)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Profile updated"
      redirect_to @user
    else
      render "edit"
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    
    flash[:warning]= "Delete user: #{user.name} "
    redirect_to users_url
  end

    private
      def user_params
        params.require(:user).permit(:name, :email,:password, :password_confirmation)
      end

      def require_login
        unless logged_in?
          flash[:danger] = "Unauthorized Access! Please login..."
          redirect_to login_url
        end
      end

      def require_admin
        redirect_to root_url unless current_user.admin?
      end

      def correct_user
        @user = User.find(params[:id])
        redirect_to root_url unless @user == current_user
      end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def login(user)
        session[:user_id] = user.id
    end

    def current_user
        User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def logout
        session.delete(:user_id)
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user,options =  {size:80})
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        img_size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?size=#{img_size}"
        
    
        image_tag(gravatar_url, alt: user.name)
    end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AwesomeBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/header"%>
    <%= render "shared/flash_messages" %>
    <div class="container p-3">
      <%= yield %>
    </div>

    <%= session[:user_id] if session[:user_id] %>
    <%= render "shared/footer"%>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="media mb-4">
    <div class="mr-2">
        <%=link_to gravatar_for(post.user, size:60), post.user %>
    </div>
    <div class="media-body">
        <h5><%= link_to post.user.name, post.user %></h5>
        <div><%= post.content%></div>
        <% if post.picture? %>
            <div>
                <%= image_tag post.picture.url, class: "mw-100"%>
            </div>
        <% end %>
        <small class="text-muted">
            Posted <%= time_ago_in_words post.created_at %> ago
        </small>
    </div>

    <% if current_user == post.user%>
        <%= link_to post, method: :delete, 
                                data: { confirm: "Are you sire? "}, 
                                class: "float-right" do%>
            <i class="fas fa-trash-alt text-muted"></i>
        <% end %>
    <% end %>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
    <div class="alert alert-danger">
        <ul>
            <% object.errors.full_messages.each do |msg| %>
                <li><%= msg %></li> 
            <% end %>
        </ul>
    </div>
<% end %>

app/views/shared/_flash_messages.html.erb
<% if flash.any? %>
    <% flash.each do |msg_type, msg| %>
      <div class="container p-2">    
        <div class="alert alert-<%= msg_type %>">
            <%= msg %>
        </div>
      </div>
    <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer class="border-top p-3">
    <div class="container">
        <small class="float-left">AwesomeBlog Application &copy; Ryohei Nakamura</small>
        <ul class="float-right">
            <li class="d-inline-block">
                <small><%= link_to "Home",root_path,class: "text-muted" %></small>
            </li>
            <li class="d-inline-block">
                <small><%= link_to "About",about_path,class: "text-muted" %></small>
            </li>
        </ul>
    </div>
</footer>

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <%# <a class="navbar-brand" href="#">AwsomeBlog</a> %>
    <%= link_to "AwsomeBlog",root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item active">
                <%= link_to "home",root_path,class: "nav-link"%>
            </li>
            <li class="nav-item">
               <%= link_to "about",about_path,class: "nav-link"%>
            </li>
            

            <% if logged_in? %>
                <li class="nav-item">
                    <%= link_to "Users",users_path, class: "nav-link" %>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <%= current_user.name %>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <%= link_to "profile", current_user,class: "dropdown-item" %>
                            <%= link_to "Settings", edit_user_path(current_user),class: "dropdown-item" %>
                        <div class="dropdown-divider"></div>
                            <%= link_to "Logout", logout_path ,method: :delete, class: "dropdown-item" %>
                    </div>
                </li>
            <% else %>
                <li class="nav-item">
                    <%# <a class="nav-link" href="#">Sign up</a> %>
                    <%= link_to "Sign up",new_user_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Login", login_path ,class: "nav-link" %>
                </li>
            <% end %>
        </ul>
    </div>
  </div>
</nav>

app/views/static_pages/about.html.erb
<div class="jumbotron">
    <h1>About</h1>
    <p>This is Ruby on Rails Application.
    A project I made in Kredo PH with Frangia PH.</p>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron">
    <h1><strong>AwesomeBlog App</strong></h1>
    <p>Welcome to AwesomeBlog!</p>

</div>

app/views/users/_follow.html.erb
<%= form_for current_user.active_relationships.build do |f| %>
    <%= hidden_field_tag :followed_id, @user.id %>
    <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_form.html.erb
 <%= form_for @user do |f| %>
    <%= render "shared/error_messages", object: f.object %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control",
                                placeholder: "Enter your name" %>
    </div>
    <div class="form-group">
        <%= f.label :email %>
        <%= f.email_field :email, class: "form-control",
                                placeholder: "Enter your email"%>
    </div>
    <div class="form-group">
        <%= f.label :password %>
        <%= f.password_field :password, class: "form-control",
                                placeholder: "Enter your password"%>
    </div>
    <div class="form-group">
        <%= f.label :password_confirmation %>
        <%= f.password_field :password_confirmation, class: "form-control",
                                placeholder: "Re-enter your password"%>
    </div>

    <%= f.submit btn_msg, class:"btn #{btn_type} btn-block" %>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for current_user.active_relationships.find_by(followed_id: @user),
                html: {method: :delete} do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-danger" %>
<% end %>

app/views/users/edit.html.erb
<div class="row">
    <div class="col-lg-6 offset-3">
        <h1 class="text-center m-4">Edit Profile</h1>
        <hr /> 
        <%= render "form", btn_msg: "Update Profile", btn_type: "btn-primary" %>
    </div>
</div>

app/views/users/home_feed.html.erb
<div class="row">
    <div class="col-lg-3">
        <div class="card">
            <div class="card-body text-center">
                <%= gravatar_for current_user %>
                <h3><%= current_user.name %></h3>
                <%= current_user.email %>
                
                <div class="row">
                    <div class="col">
                        <h4><%= current_user.following.count %></h4>
                        <small>following</small>
                    </div>
                    <div class="col">
                        <h4><%= current_user.followers.count %></h4>
                        <small>followers</small>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-9">
        <div class="card">
            <div class="card-header">
                <%= form_for @post do |f| %>
                <%= render "shared/error_messages", object: f.object %>
                <div class="form-group">               
                    <%= f.text_area :content, 
                                    class: "form-control", 
                                    placeholder: "What's on your mind" %>
                    <div class="form-group">
                        <%= f.file_field :picture, class: "mt-2" %>
                        <%= f.submit "Post", class: "btn btn-primary margin-3 float-right" %>
                    </div>
                        
                  
                <% end %>
            </div>
        </div>

        <div class="card-body">
            <% if @posts.any? %>
                <%= render @posts %>
            <% else %>
                <h4 class="text-center">Nothing to show</h4>
            <% end %>

            <div class="card-footer paginate text-center">
                <%= will_paginate @posts if @posts.any? %>
            </div>

        </div>
    </div>

</div>

app/views/users/index.html.erb
<h1 class="text-center border-bottom p-4 mb-3 ">Users</h1>
<div class="row">
    <% @users.each do |user| %>
        <div class="col-lg-6">
            <div class="media mb-3">
                <div class="align-self-center mr-3 border">
                <%# user is equivalant to "/:id" %>
                    <%= link_to gravatar_for(user), user_path(user) %>
                </div>
                <div class="media-body">
                    <h4><%= link_to user.name,user %></h4>
                </div>
                <% if current_user.admin?  || current_user == user %>
                <%= link_to "Delete", user,method: :delete, class: "btn btn-outline-danger float-right btn-sm ",
                                                    data: {confirm: "Are you sure?" } %>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

<div class="paginate text-center border-top pt-3">
    <%= will_paginate %>
</div>

app/views/users/new.html.erb
<div class="row">
    <div class="col-lg-6 offset-3">
        <h1 class="text-center m-4">Sign-up</h1>
        <hr /> 

       <%= render "form" ,btn_msg: "Signup", btn_type: "btn-info" %>
    </div>
</div>

app/views/users/show.html.erb
<div class="row jumbotron">
    <div class="col-lg-6">
        <div class="media">
            <div class="mr-3 align-self-center">
                <%= gravatar_for @user,size: 120 %>
            </div>

            <div class="media-body my-auto ">
                <h1><%= @user.name%></h1>
                <div class="row">
                    <div class="col">
                        <h4><%= @user.following.count %></h4>
                        <small>following</small>
                    </div>
                    <div class="col">
                        <h4><%= @user.followers.count %></h4>
                        <small>followers</small>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-lg-6 text-right">
        <% unless current_user == @user %>
            <% if current_user.following?(@user) %>
                <%= render "unfollow" %>
            <% else %>
                <%= render "follow" %>
            <% end %>
        <% end %>
    </div>
</div>


<div class="row">
    <div class="col-lg-8 mx-auto">
        <% if @posts.any? %>
            <%= render @posts %>
            <div class="paginate text-center">
                <%= will_paginate @posts %>
            </div>
        <% end %>
    </div>
</div>